sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"
    - "pypy"

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
    include:
    - python: 3.7
      dist: xenial
      sudo: true

env:
    - PEP8_IGNORE="E221,E501,W504"

# command to install dependencies
install:
    - pip install coverage pep8 nose

# command to run tests
# require 100% coverage (not including test files) to pass Travis CI test
# To skip pypy: - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then DOSTUFF ; fi
script:
    - export MAJOR_PYTHON_VERSION=`echo $TRAVIS_PYTHON_VERSION | cut -c 1`
    - coverage run --source=params $(which nosetests)
                   --with-doctest tests/
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage report --show-missing --fail-under=100 ; fi
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pep8 --ignore=$PEP8_IGNORE  --exclude=tests,.venv -r --show-source . ; fi
    # For convenience, make sure simple test commands work
    - python setup.py develop
    - py.test
    - nosetests

# load coverage status to https://coveralls.io
after_success:
    - 'echo travis-python: $TRAVIS_PYTHON_VERSION'
    - 'echo coveralls: $COVERALLS_REPO_TOKEN'
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls --use-mirrors ; COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls ; fi

notifications:
  email: false
  
deploy:
  provider: pypi
  password:
    secure: aVnOB13IF9Dytsk4ywV7+HQp2oAdBLvRI7SRQNDJtST8a/bpE5x4PRtstgAvq8TZkvt5TFRe+7J449mdv2faPcDqMgyfbuz1kHmevDZnUurZqZbXyT+6kYiDDvknQNh2qzFIywY2BzYRcTgTiBwv5onDooxGvvrDx53/BjHoJJBnqCS9libuqwkNresMwDdNQS3rAth3FITD4KBJ0yri1LCto8tQ6Qt488L2shI0ErmlqiQkkHely1KYuYSESeFRZ/52/E2q2peQXEBOo+Y9pmeSJkHsuZ2of6f23mGs9c8zdka2MQXnq7n6JGfIAkyDWVU93QPUX8myAkPBhm/KAEJ7IiyxnV85kqXJ8DUE42CVEopqWBFjG9yieSiH6oJ2bM7NGCaJXB/UvciTEEoS/QXoDZSvUyrKx7gKO+iO0HBH6HeRSt9QuHcXxhMKXJYNMa5bKjdJ9V3Tjt3MQJ+f9WmuCzxE7NZ17rP9vjMDJMZOsd0y+sE3cQ8V+rA7zk+CfIeV/PVeV1aSy7QrO9IXpkeeHoCdh9mMayS+rtJPKPT1hqmf+sw+iQcD5oJQnLpuqeGLVb7EvSwaLdGbtwyWFux02Pdfmfd5WQt/FVGKkga2kjMsn80av/EhGXpTaXD/2qVjAVvYfVmzCT87WDlPwcZLXRDlIfvYOKT+UxX8n1Q=

