sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"
    - "pypy"

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
    include:
    - python: 3.7
      dist: xenial
      sudo: true

env:
    - PEP8_IGNORE="E221,E501,W504"

# command to install dependencies
install:
    - pip install coverage pep8 nose

# command to run tests
# require 100% coverage (not including test files) to pass Travis CI test
# To skip pypy: - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then DOSTUFF ; fi
script:
    - export MAJOR_PYTHON_VERSION=`echo $TRAVIS_PYTHON_VERSION | cut -c 1`
    - coverage run --source=params $(which nosetests)
                   --with-doctest tests/
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage report --show-missing --fail-under=100 ; fi
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pep8 --ignore=$PEP8_IGNORE  --exclude=tests,.venv -r --show-source . ; fi
    # For convenience, make sure simple test commands work
    - python setup.py develop
    - py.test
    - nosetests

# load coverage status to https://coveralls.io
after_success:
    - 'echo travis-python: $TRAVIS_PYTHON_VERSION'
    - 'echo coveralls: $COVERALLS_REPO_TOKEN'
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls ; fi

notifications:
  email: false
  
deploy:
  provider: pypi
  username: kpe
  password:
    secure: fpf32Jy4ZN2X13nQ+01tQpBOEdpAnteNa1JrWM/JF02HwtAxLlEGtc9stMTdVv4yDOhoeU3+zxiPNbogKGEDarxfyLJmsSsCOVhi7BM7VlhPGXu64gGIyrmTVCQGnQ0ILvEkiacFNZ7qEgoTWYuh7vVUTTUopffSwTNLdpIS3IwCQdz/Gzq072Lhp+Bz5WLVPJo+F8vajYk8qBl4srYgtI3ITSHGuZCzVsqe8wrYx+z2HWwACh0dmmHa+/1+XRR/N1c9orq0mjjNJrFWUQBE+f/VJOth90Tmb/MYLccN93Akqp9AtxWe4qKFLtd6UQpK5yBx3Cf9fYZeAUU81FXxyGKC1b7jQzhNatGQrbKU0BNtoYbt1RObLv5SaYX3o7nwMTVljvJniGy0wollwg+hD78vE+CjqDeG7ooJ7UCnmc5qkPkwvrXOVo5A7WgbyMi1bdLoZB+UmUhCBW/bFu2TUD4fwblAbNCyXrpHgIi99b5Ukk3LFx1EACNyC4tNLGgw3+9DVYGJBPv90BHgBHrGjrUCB2ER41nNMVPYcjwQB8ogf+jJZCIwsoRTijJnhfkXYgvzBOA5uyBybA+IQ+3BFwQfp20DPF/2uYv80ioqmFSZKbP0ZXeW6reOBUE06Ic8V7oQO6svnnTLVA+Mxyytq0IT/mwzlwK4QxmbvoPUTHw=

